#!/usr/bin/env python3
import os
import sys
import time
import random
import asyncio
import numpy as np
import sounddevice as sd

# Ensure we can import from project root
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from vocalis.config import AppConfig
from vocalis.state import StateManager
from vocalis.ml_workers import MLWorkerPool
from vocalis.orchestrator import AssistantEngine, AskRequest
from vocalis.audio import AudioSource, SoundDeviceAudioSource, SoundDeviceAudioSink

# Import openwakeword
try:
    from openwakeword.model import Model as OWWModel
except ImportError:
    print("Error: openwakeword is not installed. Please install it using:")
    print("pip install openwakeword")
    sys.exit(1)

async def main():
    import argparse
    parser = argparse.ArgumentParser(description="Vocalis Wake Word Standby Service")
    parser.add_argument("--model", default="openwakeword_alfred.onnx", help="ONNX model filename in scripts/ directory (default: openwakeword_alfred.onnx)")
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml (default: config.yaml)")
    args = parser.parse_args()

    config_path = args.config
    if not os.path.exists(config_path):
        print(f"Error: Configuration file not found: {config_path}")
        sys.exit(1)

    # 1. Load Vocalis config
    config = AppConfig.load_yaml(config_path)
    config.resolve_paths(os.getcwd())

    # 2. Check for wake word model
    script_dir = os.path.dirname(os.path.abspath(__file__))
    wakeword_model_path = os.path.join(script_dir, args.model)
    if not os.path.exists(wakeword_model_path):
        print(f"Error: Wakeword model not found at {wakeword_model_path}")
        sys.exit(1)

    print("\n" + "="*60)
    print(" VOCALIS WAKEWORD SERVICE ")
    print("="*60)
    print(f"Wakeword Model       : {os.path.basename(wakeword_model_path)}")
    print(f"Microphone Device    : {config.audio.input_device_index}")
    print(f"Speaker Device       : {config.audio.output_device_index}")
    print(f"Digital Input Gain   : {config.audio.gain}x")
    print("-"*60)

    # 3. Initialize openwakeword model
    print("Initializing openWakeWord (downloading resource models if needed)...")
    try:
        oww_model = OWWModel(
            wakeword_models=[wakeword_model_path],
            inference_framework="onnx"
        )
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"Error initializing openWakeWord: {e}")
        print("Please check that internet is available for downloading required MelSpectrogram/Embedding models.")
        sys.exit(1)

    # Get the key name generated by openwakeword
    dummy_input = np.zeros(1280, dtype=np.int16)
    predictions = oww_model.predict(dummy_input)
    prediction_keys = list(predictions.keys())
    if not prediction_keys:
        print("Error: No prediction keys loaded in openWakeWord model.")
        sys.exit(1)
    target_key = prediction_keys[0]
    print(f"Loaded wakeword key  : '{target_key}'")

    # 4. Start up Vocalis Core
    print("Starting Vocalis ML Worker Pool...")
    state_manager = StateManager()
    ml_pool = MLWorkerPool(config)
    engine = AssistantEngine(config, state_manager, ml_pool)

    # Initialize Audio interfaces
    source = SoundDeviceAudioSource(
        device_index=config.audio.input_device_index,
        sample_rate=config.audio.sample_rate,
        channels=config.audio.channels,
        chunk_size=config.audio.chunk_size,
        gain=config.audio.gain
    )
    sink = SoundDeviceAudioSink(
        device_index=config.audio.output_device_index,
        sample_rate=config.audio.sample_rate,
        channels=config.audio.channels
    )

    # Define Spanish wake responses
    wake_responses = [
        "¿Qué desea?",
        "¿Cómo puedo ayudar?",
        "Sí, mi señor"
    ]

    # We create a queue for routing chunks to engine.ask
    command_queue = asyncio.Queue()
    
    class StandbyCommandSource(AudioSource):
        async def read_chunks(self):
            # yield chunks from our command_queue
            while True:
                chunk = await command_queue.get()
                yield chunk

    ask_source = StandbyCommandSource()
    
    # State tracking
    mode = "standby"  # "standby" or "ask"
    
    # openwakeword expects 80ms chunks = 1280 samples at 16000Hz
    samples_needed = 1280
    bytes_needed = samples_needed * 2
    audio_buffer = bytearray()
    model_display_name = args.model.replace("openwakeword_", "").replace(".onnx", "").replace("_", " ").title()

    print(f"\n[Standby] mode active. Say '{model_display_name}' to wake...")
    print("Press Ctrl+C to exit.")
    print("="*60 + "\n")

    try:
        # Read from source generator permanently (no stream closing/re-opening)
        async for chunk in source.read_chunks():
            if mode == "standby":
                audio_buffer.extend(chunk)
                
                while len(audio_buffer) >= bytes_needed:
                    chunk_bytes = audio_buffer[:bytes_needed]
                    del audio_buffer[:bytes_needed]
                    
                    pcm16 = np.frombuffer(chunk_bytes, dtype=np.int16)
                    
                    # Run inference
                    predictions = oww_model.predict(pcm16)
                    score = predictions.get(target_key, 0.0)
                    
                    # Print small volume/score monitor
                    rms = np.sqrt(np.mean(pcm16.astype(np.float32)**2)) if len(pcm16) > 0 else 0.0
                    bar_len = int(rms / 100)
                    bar = "=" * min(bar_len, 20)
                    spaces = " " * (20 - len(bar))
                    sys.stdout.write(f"\rVolume: [ {bar}{spaces} ] | Score: {score:.3f}")
                    sys.stdout.flush()

                    # Threshold trigger
                    if score >= 0.50:
                        sys.stdout.write("\n")
                        print("\n" + "*"*40)
                        print(f" WAKE DETECTED! (Score: {score:.3f})")
                        print("*"*40)
                        
                        # Switch mode to route incoming audio to the command capture queue
                        mode = "ask"
                        
                        # Clear any stale data in command queue
                        while not command_queue.empty():
                            try:
                                command_queue.get_nowait()
                            except asyncio.QueueEmpty:
                                break
                                
                        # Run the ask pipeline in a background task so we keep routing audio chunks
                        async def run_ask_task():
                            nonlocal mode
                            prompt = random.choice(wake_responses)
                            print(f"Wake prompt: '{prompt}'")
                            
                            request = AskRequest(
                                context_id=f"wake_{int(time.time())}",
                                tts_text=prompt,
                                require_speaker_id=False,
                                output_format="both",
                                barge_in=True
                            )
                            
                            try:
                                result = await engine.ask(request, ask_source, sink)
                                print("\n" + "-"*40)
                                print(f"Status           : {result.status}")
                                print(f"ASR Decoded Text : '{result.transcription}'")
                                print(f"Verified Speaker : '{result.speaker}'")
                                print("-"*40 + "\n")
                            except Exception as e:
                                print(f"\nError in Vocalis Ask pipeline: {e}\n")
                            
                            # Clear old features/leftovers
                            oww_model.reset()
                            audio_buffer.clear()
                            
                            # Switch back to standby
                            mode = "standby"
                            print(f"\n[Standby] mode active. Say '{model_display_name}' to wake...")
                            print("Press Ctrl+C to exit.")
                            print("="*60 + "\n")
                            
                        asyncio.create_task(run_ask_task())
                        break  # Break slice loop, return to generator stream loop
                        
            elif mode == "ask":
                # Route audio real-time to the ask pipeline
                command_queue.put_nowait(chunk)

    except KeyboardInterrupt:
        print("\nExiting wake service...")
    finally:
        print("Closing resources...")
        await source.close()
        ml_pool.close()
        print("Goodbye!")

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
